name: Playwright Tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "*/5 * * * *"
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    container: anthonyshull/node-runner:latest
    env:
      TARGET_URL: http://dev-blue.mbtace.com
    steps:
    - uses: actions/checkout@v3
    - name: Run Playwright tests
      run: npx playwright test
      env:
        TARGET_URL: http://dev-blue.mbtace.com
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
