name: Playwright Tests
on:
  push:
    branches: [main]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    container:
      image: anthonyshull/node-runner:latest
      volumes:
        - ${{ github.workspace }}:/app
    env:
      TARGET_URL: http://dev-blue.mbtace.com
    steps:
    - name: Checkout the repo
      uses: actions/checkout@v3
    - name: Run Playwright tests
      run: npx playwright test
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
